### PR TITLE
add info about `Test.createTestingModule` limitation

### PR DESCRIPTION
**Pull request by micalevisk**

### CODE REVIEW

**Comment by micalevisk** [comment]
@Sikora00 do you mind on adding the label `hacktoberfest-accepted` to this PR? or just add the topic `hacktoberfest` to the repository :)

**Comment by Sikora00** [comment]
Why hacktoberferst @micalevisk? 😅
What's that?

**Comment by micalevisk** [comment]
@Sikora00 it's an event that happen every october. https://hacktoberfest.com People participate by contributing to repos on github or gitlab

I'm trying to get some badges :p

**Comment by Sikora00** [comment]
Sounds cool. Looking for more of such contributions ;)

**Pull request merged**
